### PR TITLE
fix(#1270) : 解决 AtButton formType='submit' 微信小程序下不能触发事件 #1270

### LINKED ISSUE #1491: form 表单小程序提交事件报错
版本：taro-ui 3.1.0-beta.2
 form 表单组件提交事件onSubmit，H5就可以正常使用，运行小程序报错，
image

image

### PR DESCRIPTION
**Pull request by dengxiang**

### CODE REVIEW

File: packages/taro-ui/src/components/button/index.tsx [hunk 1]
```diff
@@ -62,30 +62,6 @@ export default class AtButton extends React.Component<
     this.props.onOpenSetting && this.props.onOpenSetting(event)
   }
```
Comment (shinken008) [inline packages/taro-ui/src/components/button/index.tsx:64]: https://developers.weixin.qq.com/miniprogram/dev/component/form.html

微信端需加上 behaviors = ['wx://form-field']
